//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Data.Entity.Infrastructure.MappingViews;

[assembly: DbMappingViewCacheTypeAttribute(
    typeof(BookCompanyManagement.DAL.BcContext),
    typeof(Edm_EntityMappingGeneratedViews.ViewsForBaseEntitySetsddc694e506fe1f043ccb64fe0e3f2104ad6d8dc89d390ef2131ff9ddbc5700a5))]

namespace Edm_EntityMappingGeneratedViews
{
    using System;
    using System.CodeDom.Compiler;
    using System.Data.Entity.Core.Metadata.Edm;

    /// <summary>
    /// Implements a mapping view cache.
    /// </summary>
    [GeneratedCode("Entity Framework Power Tools", "0.9.0.0")]
    internal sealed class ViewsForBaseEntitySetsddc694e506fe1f043ccb64fe0e3f2104ad6d8dc89d390ef2131ff9ddbc5700a5 : DbMappingViewCache
    {
        /// <summary>
        /// Gets a hash value computed over the mapping closure.
        /// </summary>
        public override string MappingHashValue
        {
            get { return "ddc694e506fe1f043ccb64fe0e3f2104ad6d8dc89d390ef2131ff9ddbc5700a5"; }
        }

        /// <summary>
        /// Gets a view corresponding to the specified extent.
        /// </summary>
        /// <param name="extent">The extent.</param>
        /// <returns>The mapping view, or null if the extent is not associated with a mapping view.</returns>
        public override DbMappingView GetView(EntitySetBase extent)
        {
            if (extent == null)
            {
                throw new ArgumentNullException("extent");
            }

            var extentName = extent.EntityContainer.Name + "." + extent.Name;

            if (extentName == "CodeFirstDatabase.BookCompany")
            {
                return GetView0();
            }

            if (extentName == "CodeFirstDatabase.BookPrintOrder")
            {
                return GetView1();
            }

            if (extentName == "CodeFirstDatabase.Book")
            {
                return GetView2();
            }

            if (extentName == "CodeFirstDatabase.Paper")
            {
                return GetView3();
            }

            if (extentName == "CodeFirstDatabase.PaperBrand")
            {
                return GetView4();
            }

            if (extentName == "CodeFirstDatabase.PaperMill")
            {
                return GetView5();
            }

            if (extentName == "CodeFirstDatabase.PaperSpec")
            {
                return GetView6();
            }

            if (extentName == "CodeFirstDatabase.PaperInstock")
            {
                return GetView7();
            }

            if (extentName == "CodeFirstDatabase.PrintShop")
            {
                return GetView8();
            }

            if (extentName == "CodeFirstDatabase.PaperMakingOrder")
            {
                return GetView9();
            }

            if (extentName == "CodeFirstDatabase.PaperNeed")
            {
                return GetView10();
            }

            if (extentName == "CodeFirstDatabase.BookInstock")
            {
                return GetView11();
            }

            if (extentName == "BcContext.BookCompany")
            {
                return GetView12();
            }

            if (extentName == "BcContext.BookPrintOrders")
            {
                return GetView13();
            }

            if (extentName == "BcContext.BookPrintOrder_Paper")
            {
                return GetView14();
            }

            if (extentName == "BcContext.Books")
            {
                return GetView15();
            }

            if (extentName == "BcContext.Papers")
            {
                return GetView16();
            }

            if (extentName == "BcContext.PaperBrands")
            {
                return GetView17();
            }

            if (extentName == "BcContext.Papermills")
            {
                return GetView18();
            }

            if (extentName == "BcContext.Paperspec")
            {
                return GetView19();
            }

            if (extentName == "BcContext.PaperInstcok")
            {
                return GetView20();
            }

            if (extentName == "BcContext.PaperSpec_PaperInstocks")
            {
                return GetView21();
            }

            if (extentName == "BcContext.Printshop")
            {
                return GetView22();
            }

            if (extentName == "BcContext.PapermakingOrder")
            {
                return GetView23();
            }

            if (extentName == "BcContext.PaperSpec_PaperMakingOrders")
            {
                return GetView24();
            }

            if (extentName == "BcContext.PaperNeeds")
            {
                return GetView25();
            }

            if (extentName == "BcContext.BookInstocks")
            {
                return GetView26();
            }

            return null;
        }

        /// <summary>
        /// Gets the view for CodeFirstDatabase.BookCompany.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView0()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing BookCompany
        [CodeFirstDatabaseSchema.BookCompany](T1.BookCompany_BookCompanyId, T1.BookCompany_BookCompanyName, T1.BookCompany_BookCompanyDescription, T1.BookCompany_IsDeleted)
    FROM (
        SELECT 
            T.BookCompanyId AS BookCompany_BookCompanyId, 
            T.BookCompanyName AS BookCompany_BookCompanyName, 
            T.BookCompanyDescription AS BookCompany_BookCompanyDescription, 
            T.IsDeleted AS BookCompany_IsDeleted, 
            True AS _from0
        FROM BcContext.BookCompany AS T
    ) AS T1");
        }

        /// <summary>
        /// Gets the view for CodeFirstDatabase.BookPrintOrder.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView1()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing BookPrintOrder
        [CodeFirstDatabaseSchema.BookPrintOrder](T3.BookPrintOrder_BookPrintOrderId, T3.BookPrintOrder_BookPrintOrderName, T3.BookPrintOrder_BookPrintMount, T3.BookPrintOrder_OrderStatus, T3.BookPrintOrder_CreateDateTime, T3.BookPrintOrder_CopmleteDateTime, T3.BookPrintOrder_BookId, T3.BookPrintOrder_BookCompanyId, T3.BookPrintOrder_PrintShopId, T3.[BookPrintOrder.Paper_PaperId])
    FROM (
        SELECT T1.BookPrintOrder_BookPrintOrderId, T1.BookPrintOrder_BookPrintOrderName, T1.BookPrintOrder_BookPrintMount, T1.BookPrintOrder_OrderStatus, T1.BookPrintOrder_CreateDateTime, T1.BookPrintOrder_CopmleteDateTime, T1.BookPrintOrder_BookId, T1.BookPrintOrder_BookCompanyId, T1.BookPrintOrder_PrintShopId, T2.[BookPrintOrder.Paper_PaperId], T1._from0, (T2._from1 AND T2._from1 IS NOT NULL) AS _from1
        FROM  (
            SELECT 
                T.BookPrintOrderId AS BookPrintOrder_BookPrintOrderId, 
                T.BookPrintOrderName AS BookPrintOrder_BookPrintOrderName, 
                T.BookPrintMount AS BookPrintOrder_BookPrintMount, 
                CAST(T.OrderStatus AS [Edm.Int32]) AS BookPrintOrder_OrderStatus, 
                T.CreateDateTime AS BookPrintOrder_CreateDateTime, 
                T.CopmleteDateTime AS BookPrintOrder_CopmleteDateTime, 
                T.BookId AS BookPrintOrder_BookId, 
                T.BookCompanyId AS BookPrintOrder_BookCompanyId, 
                T.PrintShopId AS BookPrintOrder_PrintShopId, 
                True AS _from0
            FROM BcContext.BookPrintOrders AS T) AS T1
            LEFT OUTER JOIN (
            SELECT 
                Key(T.BookPrintOrder_Paper_Source).BookPrintOrderId AS BookPrintOrder_BookPrintOrderId, 
                Key(T.BookPrintOrder_Paper_Target).PaperId AS [BookPrintOrder.Paper_PaperId], 
                True AS _from1
            FROM BcContext.BookPrintOrder_Paper AS T) AS T2
            ON T1.BookPrintOrder_BookPrintOrderId = T2.BookPrintOrder_BookPrintOrderId
    ) AS T3");
        }

        /// <summary>
        /// Gets the view for CodeFirstDatabase.Book.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView2()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing Book
        [CodeFirstDatabaseSchema.Book](T1.Book_BookId, T1.Book_BookName)
    FROM (
        SELECT 
            T.BookId AS Book_BookId, 
            T.BookName AS Book_BookName, 
            True AS _from0
        FROM BcContext.Books AS T
    ) AS T1");
        }

        /// <summary>
        /// Gets the view for CodeFirstDatabase.Paper.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView3()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing Paper
        [CodeFirstDatabaseSchema.Paper](T1.Paper_PaperId, T1.Paper_PaperName, T1.Paper_IsDeleted, T1.Paper_PaperBrandId, T1.Paper_PaperSpecId)
    FROM (
        SELECT 
            T.PaperId AS Paper_PaperId, 
            T.PaperName AS Paper_PaperName, 
            T.IsDeleted AS Paper_IsDeleted, 
            T.PaperBrandId AS Paper_PaperBrandId, 
            T.PaperSpecId AS Paper_PaperSpecId, 
            True AS _from0
        FROM BcContext.Papers AS T
    ) AS T1");
        }

        /// <summary>
        /// Gets the view for CodeFirstDatabase.PaperBrand.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView4()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing PaperBrand
        [CodeFirstDatabaseSchema.PaperBrand](T1.PaperBrand_PaperBrandId, T1.PaperBrand_PaperBrandName, T1.PaperBrand_PaperMillId)
    FROM (
        SELECT 
            T.PaperBrandId AS PaperBrand_PaperBrandId, 
            T.PaperBrandName AS PaperBrand_PaperBrandName, 
            T.PaperMillId AS PaperBrand_PaperMillId, 
            True AS _from0
        FROM BcContext.PaperBrands AS T
    ) AS T1");
        }

        /// <summary>
        /// Gets the view for CodeFirstDatabase.PaperMill.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView5()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing PaperMill
        [CodeFirstDatabaseSchema.PaperMill](T1.PaperMill_PaperMillId, T1.PaperMill_PaperMillName)
    FROM (
        SELECT 
            T.PaperMillId AS PaperMill_PaperMillId, 
            T.PaperMillName AS PaperMill_PaperMillName, 
            True AS _from0
        FROM BcContext.Papermills AS T
    ) AS T1");
        }

        /// <summary>
        /// Gets the view for CodeFirstDatabase.PaperSpec.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView6()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing PaperSpec
        [CodeFirstDatabaseSchema.PaperSpec](T1.PaperSpec_PaperSpecId, T1.PaperSpec_PaperSpecName, T1.PaperSpec_PaperType, T1.PaperSpec_PaperWeight, T1.PaperSpec_PaperSize, T1.PaperSpec_PaperDescription, T1.PaperSpec_IsDeleted)
    FROM (
        SELECT 
            T.PaperSpecId AS PaperSpec_PaperSpecId, 
            T.PaperSpecName AS PaperSpec_PaperSpecName, 
            T.PaperType AS PaperSpec_PaperType, 
            T.PaperWeight AS PaperSpec_PaperWeight, 
            T.PaperSize AS PaperSpec_PaperSize, 
            T.PaperDescription AS PaperSpec_PaperDescription, 
            T.IsDeleted AS PaperSpec_IsDeleted, 
            True AS _from0
        FROM BcContext.Paperspec AS T
    ) AS T1");
        }

        /// <summary>
        /// Gets the view for CodeFirstDatabase.PaperInstock.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView7()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing PaperInstock
        [CodeFirstDatabaseSchema.PaperInstock](T3.PaperInstock_PaperInstockId, T3.PaperInstock_PaperInstockNname, T3.PaperInstock_PaperMount, T3.PaperInstock_PaperId, T3.PaperInstock_PrintShopId, T3.[PaperInstock.PaperSpec_PaperSpecId])
    FROM (
        SELECT T1.PaperInstock_PaperInstockId, T1.PaperInstock_PaperInstockNname, T1.PaperInstock_PaperMount, T1.PaperInstock_PaperId, T1.PaperInstock_PrintShopId, T2.[PaperInstock.PaperSpec_PaperSpecId], T1._from0, (T2._from1 AND T2._from1 IS NOT NULL) AS _from1
        FROM  (
            SELECT 
                T.PaperInstockId AS PaperInstock_PaperInstockId, 
                T.PaperInstockNname AS PaperInstock_PaperInstockNname, 
                T.PaperMount AS PaperInstock_PaperMount, 
                T.PaperId AS PaperInstock_PaperId, 
                T.PrintShopId AS PaperInstock_PrintShopId, 
                True AS _from0
            FROM BcContext.PaperInstcok AS T) AS T1
            LEFT OUTER JOIN (
            SELECT 
                Key(T.PaperSpec_PaperInstocks_Target).PaperInstockId AS PaperInstock_PaperInstockId, 
                Key(T.PaperSpec_PaperInstocks_Source).PaperSpecId AS [PaperInstock.PaperSpec_PaperSpecId], 
                True AS _from1
            FROM BcContext.PaperSpec_PaperInstocks AS T) AS T2
            ON T1.PaperInstock_PaperInstockId = T2.PaperInstock_PaperInstockId
    ) AS T3");
        }

        /// <summary>
        /// Gets the view for CodeFirstDatabase.PrintShop.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView8()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing PrintShop
        [CodeFirstDatabaseSchema.PrintShop](T1.PrintShop_PrintShopId, T1.PrintShop_PrintShopName, T1.PrintShop_PrintShopDescription, T1.PrintShop_IsDeleted)
    FROM (
        SELECT 
            T.PrintShopId AS PrintShop_PrintShopId, 
            T.PrintShopName AS PrintShop_PrintShopName, 
            T.PrintShopDescription AS PrintShop_PrintShopDescription, 
            T.IsDeleted AS PrintShop_IsDeleted, 
            True AS _from0
        FROM BcContext.Printshop AS T
    ) AS T1");
        }

        /// <summary>
        /// Gets the view for CodeFirstDatabase.PaperMakingOrder.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView9()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing PaperMakingOrder
        [CodeFirstDatabaseSchema.PaperMakingOrder](T3.PaperMakingOrder_PaperMakingOrderId, T3.PaperMakingOrder_PaperMakingOrderName, T3.PaperMakingOrder_PaperMount, T3.PaperMakingOrder_OrderStatus, T3.PaperMakingOrder_CreateDateTime, T3.PaperMakingOrder_CopmleteDateTime, T3.PaperMakingOrder_BookCompanyId, T3.PaperMakingOrder_PaperId, T3.PaperMakingOrder_PrintShopId, T3.[PaperMakingOrder.PaperSpec_PaperSpecId])
    FROM (
        SELECT T1.PaperMakingOrder_PaperMakingOrderId, T1.PaperMakingOrder_PaperMakingOrderName, T1.PaperMakingOrder_PaperMount, T1.PaperMakingOrder_OrderStatus, T1.PaperMakingOrder_CreateDateTime, T1.PaperMakingOrder_CopmleteDateTime, T1.PaperMakingOrder_BookCompanyId, T1.PaperMakingOrder_PaperId, T1.PaperMakingOrder_PrintShopId, T2.[PaperMakingOrder.PaperSpec_PaperSpecId], T1._from0, (T2._from1 AND T2._from1 IS NOT NULL) AS _from1
        FROM  (
            SELECT 
                T.PaperMakingOrderId AS PaperMakingOrder_PaperMakingOrderId, 
                T.PaperMakingOrderName AS PaperMakingOrder_PaperMakingOrderName, 
                T.PaperMount AS PaperMakingOrder_PaperMount, 
                CAST(T.OrderStatus AS [Edm.Int32]) AS PaperMakingOrder_OrderStatus, 
                T.CreateDateTime AS PaperMakingOrder_CreateDateTime, 
                T.CopmleteDateTime AS PaperMakingOrder_CopmleteDateTime, 
                T.BookCompanyId AS PaperMakingOrder_BookCompanyId, 
                T.PaperId AS PaperMakingOrder_PaperId, 
                T.PrintShopId AS PaperMakingOrder_PrintShopId, 
                True AS _from0
            FROM BcContext.PapermakingOrder AS T) AS T1
            LEFT OUTER JOIN (
            SELECT 
                Key(T.PaperSpec_PaperMakingOrders_Target).PaperMakingOrderId AS PaperMakingOrder_PaperMakingOrderId, 
                Key(T.PaperSpec_PaperMakingOrders_Source).PaperSpecId AS [PaperMakingOrder.PaperSpec_PaperSpecId], 
                True AS _from1
            FROM BcContext.PaperSpec_PaperMakingOrders AS T) AS T2
            ON T1.PaperMakingOrder_PaperMakingOrderId = T2.PaperMakingOrder_PaperMakingOrderId
    ) AS T3");
        }

        /// <summary>
        /// Gets the view for CodeFirstDatabase.PaperNeed.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView10()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing PaperNeed
        [CodeFirstDatabaseSchema.PaperNeed](T1.PaperNeed_PaperNeedId, T1.PaperNeed_PaperNeedName, T1.PaperNeed_PaperId, T1.PaperNeed_PaperNeedMount, T1.PaperNeed_BookPrintOrderId)
    FROM (
        SELECT 
            T.PaperNeedId AS PaperNeed_PaperNeedId, 
            T.PaperNeedName AS PaperNeed_PaperNeedName, 
            T.PaperId AS PaperNeed_PaperId, 
            T.PaperNeedMount AS PaperNeed_PaperNeedMount, 
            T.BookPrintOrderId AS PaperNeed_BookPrintOrderId, 
            True AS _from0
        FROM BcContext.PaperNeeds AS T
    ) AS T1");
        }

        /// <summary>
        /// Gets the view for CodeFirstDatabase.BookInstock.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView11()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing BookInstock
        [CodeFirstDatabaseSchema.BookInstock](T1.BookInstock_BookInstockId, T1.BookInstock_BookInstockNname, T1.BookInstock_BookMount, T1.BookInstock_PaperId, T1.BookInstock_PrintShopId)
    FROM (
        SELECT 
            T.BookInstockId AS BookInstock_BookInstockId, 
            T.BookInstockNname AS BookInstock_BookInstockNname, 
            T.BookMount AS BookInstock_BookMount, 
            T.PaperId AS BookInstock_PaperId, 
            T.PrintShopId AS BookInstock_PrintShopId, 
            True AS _from0
        FROM BcContext.BookInstocks AS T
    ) AS T1");
        }

        /// <summary>
        /// Gets the view for BcContext.BookCompany.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView12()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing BookCompany
        [BookCompanyManagement.DAL.BookCompany](T1.BookCompany_BookCompanyId, T1.BookCompany_BookCompanyName, T1.BookCompany_BookCompanyDescription, T1.BookCompany_IsDeleted)
    FROM (
        SELECT 
            T.BookCompanyId AS BookCompany_BookCompanyId, 
            T.BookCompanyName AS BookCompany_BookCompanyName, 
            T.BookCompanyDescription AS BookCompany_BookCompanyDescription, 
            T.IsDeleted AS BookCompany_IsDeleted, 
            True AS _from0
        FROM CodeFirstDatabase.BookCompany AS T
    ) AS T1");
        }

        /// <summary>
        /// Gets the view for BcContext.BookPrintOrders.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView13()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing BookPrintOrders
        [BookCompanyManagement.DAL.BookPrintOrder](T1.BookPrintOrder_BookPrintOrderId, T1.BookPrintOrder_BookPrintOrderName, T1.BookPrintOrder_BookPrintMount, T1.BookPrintOrder_OrderStatus, T1.BookPrintOrder_CreateDateTime, T1.BookPrintOrder_CopmleteDateTime, T1.BookPrintOrder_BookId, T1.BookPrintOrder_BookCompanyId, T1.BookPrintOrder_PrintShopId) WITH 
        RELATIONSHIP(CREATEREF(BcContext.Papers, ROW(T1.[BookPrintOrder_Paper.BookPrintOrder_Paper_Target.PaperId]),[BookCompanyManagement.DAL.Paper]),[BookCompanyManagement.DAL.BookPrintOrder_Paper],BookPrintOrder_Paper_Source,BookPrintOrder_Paper_Target) 
    FROM (
        SELECT 
            T.BookPrintOrderId AS BookPrintOrder_BookPrintOrderId, 
            T.BookPrintOrderName AS BookPrintOrder_BookPrintOrderName, 
            T.BookPrintMount AS BookPrintOrder_BookPrintMount, 
            CAST(T.OrderStatus AS [BookCompanyManagement.DAL.PaperOrderStatus]) AS BookPrintOrder_OrderStatus, 
            T.CreateDateTime AS BookPrintOrder_CreateDateTime, 
            T.CopmleteDateTime AS BookPrintOrder_CopmleteDateTime, 
            T.BookId AS BookPrintOrder_BookId, 
            T.BookCompanyId AS BookPrintOrder_BookCompanyId, 
            T.PrintShopId AS BookPrintOrder_PrintShopId, 
            True AS _from0, 
            T.Paper_PaperId AS [BookPrintOrder_Paper.BookPrintOrder_Paper_Target.PaperId]
        FROM CodeFirstDatabase.BookPrintOrder AS T
    ) AS T1");
        }

        /// <summary>
        /// Gets the view for BcContext.BookPrintOrder_Paper.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView14()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing BookPrintOrder_Paper
        [BookCompanyManagement.DAL.BookPrintOrder_Paper](T3.[BookPrintOrder_Paper.BookPrintOrder_Paper_Source], T3.[BookPrintOrder_Paper.BookPrintOrder_Paper_Target])
    FROM (
        SELECT -- Constructing BookPrintOrder_Paper_Source
            CreateRef(BcContext.BookPrintOrders, row(T2.[BookPrintOrder_Paper.BookPrintOrder_Paper_Source.BookPrintOrderId]), [BookCompanyManagement.DAL.BookPrintOrder]) AS [BookPrintOrder_Paper.BookPrintOrder_Paper_Source], 
            T2.[BookPrintOrder_Paper.BookPrintOrder_Paper_Target]
        FROM (
            SELECT -- Constructing BookPrintOrder_Paper_Target
                T1.[BookPrintOrder_Paper.BookPrintOrder_Paper_Source.BookPrintOrderId], 
                CreateRef(BcContext.Papers, row(T1.[BookPrintOrder_Paper.BookPrintOrder_Paper_Target.PaperId]), [BookCompanyManagement.DAL.Paper]) AS [BookPrintOrder_Paper.BookPrintOrder_Paper_Target]
            FROM (
                SELECT 
                    T.BookPrintOrderId AS [BookPrintOrder_Paper.BookPrintOrder_Paper_Source.BookPrintOrderId], 
                    T.Paper_PaperId AS [BookPrintOrder_Paper.BookPrintOrder_Paper_Target.PaperId], 
                    True AS _from0
                FROM CodeFirstDatabase.BookPrintOrder AS T
                WHERE T.Paper_PaperId IS NOT NULL
            ) AS T1
        ) AS T2
    ) AS T3");
        }

        /// <summary>
        /// Gets the view for BcContext.Books.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView15()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing Books
        [BookCompanyManagement.DAL.Book](T1.Book_BookId, T1.Book_BookName)
    FROM (
        SELECT 
            T.BookId AS Book_BookId, 
            T.BookName AS Book_BookName, 
            True AS _from0
        FROM CodeFirstDatabase.Book AS T
    ) AS T1");
        }

        /// <summary>
        /// Gets the view for BcContext.Papers.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView16()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing Papers
        [BookCompanyManagement.DAL.Paper](T1.Paper_PaperId, T1.Paper_PaperName, T1.Paper_IsDeleted, T1.Paper_PaperBrandId, T1.Paper_PaperSpecId)
    FROM (
        SELECT 
            T.PaperId AS Paper_PaperId, 
            T.PaperName AS Paper_PaperName, 
            T.IsDeleted AS Paper_IsDeleted, 
            T.PaperBrandId AS Paper_PaperBrandId, 
            T.PaperSpecId AS Paper_PaperSpecId, 
            True AS _from0
        FROM CodeFirstDatabase.Paper AS T
    ) AS T1");
        }

        /// <summary>
        /// Gets the view for BcContext.PaperBrands.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView17()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing PaperBrands
        [BookCompanyManagement.DAL.PaperBrand](T1.PaperBrand_PaperBrandId, T1.PaperBrand_PaperBrandName, T1.PaperBrand_PaperMillId)
    FROM (
        SELECT 
            T.PaperBrandId AS PaperBrand_PaperBrandId, 
            T.PaperBrandName AS PaperBrand_PaperBrandName, 
            T.PaperMillId AS PaperBrand_PaperMillId, 
            True AS _from0
        FROM CodeFirstDatabase.PaperBrand AS T
    ) AS T1");
        }

        /// <summary>
        /// Gets the view for BcContext.Papermills.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView18()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing Papermills
        [BookCompanyManagement.DAL.PaperMill](T1.PaperMill_PaperMillId, T1.PaperMill_PaperMillName)
    FROM (
        SELECT 
            T.PaperMillId AS PaperMill_PaperMillId, 
            T.PaperMillName AS PaperMill_PaperMillName, 
            True AS _from0
        FROM CodeFirstDatabase.PaperMill AS T
    ) AS T1");
        }

        /// <summary>
        /// Gets the view for BcContext.Paperspec.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView19()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing Paperspec
        [BookCompanyManagement.DAL.PaperSpec](T1.PaperSpec_PaperSpecId, T1.PaperSpec_PaperSpecName, T1.PaperSpec_PaperType, T1.PaperSpec_PaperWeight, T1.PaperSpec_PaperSize, T1.PaperSpec_PaperDescription, T1.PaperSpec_IsDeleted)
    FROM (
        SELECT 
            T.PaperSpecId AS PaperSpec_PaperSpecId, 
            T.PaperSpecName AS PaperSpec_PaperSpecName, 
            T.PaperType AS PaperSpec_PaperType, 
            T.PaperWeight AS PaperSpec_PaperWeight, 
            T.PaperSize AS PaperSpec_PaperSize, 
            T.PaperDescription AS PaperSpec_PaperDescription, 
            T.IsDeleted AS PaperSpec_IsDeleted, 
            True AS _from0
        FROM CodeFirstDatabase.PaperSpec AS T
    ) AS T1");
        }

        /// <summary>
        /// Gets the view for BcContext.PaperInstcok.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView20()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing PaperInstcok
        [BookCompanyManagement.DAL.PaperInstock](T1.PaperInstock_PaperInstockId, T1.PaperInstock_PaperInstockNname, T1.PaperInstock_PaperMount, T1.PaperInstock_PaperId, T1.PaperInstock_PrintShopId) WITH 
        RELATIONSHIP(CREATEREF(BcContext.Paperspec, ROW(T1.[PaperSpec_PaperInstocks.PaperSpec_PaperInstocks_Source.PaperSpecId]),[BookCompanyManagement.DAL.PaperSpec]),[BookCompanyManagement.DAL.PaperSpec_PaperInstocks],PaperSpec_PaperInstocks_Target,PaperSpec_PaperInstocks_Source) 
    FROM (
        SELECT 
            T.PaperInstockId AS PaperInstock_PaperInstockId, 
            T.PaperInstockNname AS PaperInstock_PaperInstockNname, 
            T.PaperMount AS PaperInstock_PaperMount, 
            T.PaperId AS PaperInstock_PaperId, 
            T.PrintShopId AS PaperInstock_PrintShopId, 
            True AS _from0, 
            T.PaperSpec_PaperSpecId AS [PaperSpec_PaperInstocks.PaperSpec_PaperInstocks_Source.PaperSpecId]
        FROM CodeFirstDatabase.PaperInstock AS T
    ) AS T1");
        }

        /// <summary>
        /// Gets the view for BcContext.PaperSpec_PaperInstocks.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView21()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing PaperSpec_PaperInstocks
        [BookCompanyManagement.DAL.PaperSpec_PaperInstocks](T3.[PaperSpec_PaperInstocks.PaperSpec_PaperInstocks_Source], T3.[PaperSpec_PaperInstocks.PaperSpec_PaperInstocks_Target])
    FROM (
        SELECT -- Constructing PaperSpec_PaperInstocks_Source
            CreateRef(BcContext.Paperspec, row(T2.[PaperSpec_PaperInstocks.PaperSpec_PaperInstocks_Source.PaperSpecId]), [BookCompanyManagement.DAL.PaperSpec]) AS [PaperSpec_PaperInstocks.PaperSpec_PaperInstocks_Source], 
            T2.[PaperSpec_PaperInstocks.PaperSpec_PaperInstocks_Target]
        FROM (
            SELECT -- Constructing PaperSpec_PaperInstocks_Target
                T1.[PaperSpec_PaperInstocks.PaperSpec_PaperInstocks_Source.PaperSpecId], 
                CreateRef(BcContext.PaperInstcok, row(T1.[PaperSpec_PaperInstocks.PaperSpec_PaperInstocks_Target.PaperInstockId]), [BookCompanyManagement.DAL.PaperInstock]) AS [PaperSpec_PaperInstocks.PaperSpec_PaperInstocks_Target]
            FROM (
                SELECT 
                    T.PaperSpec_PaperSpecId AS [PaperSpec_PaperInstocks.PaperSpec_PaperInstocks_Source.PaperSpecId], 
                    T.PaperInstockId AS [PaperSpec_PaperInstocks.PaperSpec_PaperInstocks_Target.PaperInstockId], 
                    True AS _from0
                FROM CodeFirstDatabase.PaperInstock AS T
                WHERE T.PaperSpec_PaperSpecId IS NOT NULL
            ) AS T1
        ) AS T2
    ) AS T3");
        }

        /// <summary>
        /// Gets the view for BcContext.Printshop.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView22()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing Printshop
        [BookCompanyManagement.DAL.PrintShop](T1.PrintShop_PrintShopId, T1.PrintShop_PrintShopName, T1.PrintShop_PrintShopDescription, T1.PrintShop_IsDeleted)
    FROM (
        SELECT 
            T.PrintShopId AS PrintShop_PrintShopId, 
            T.PrintShopName AS PrintShop_PrintShopName, 
            T.PrintShopDescription AS PrintShop_PrintShopDescription, 
            T.IsDeleted AS PrintShop_IsDeleted, 
            True AS _from0
        FROM CodeFirstDatabase.PrintShop AS T
    ) AS T1");
        }

        /// <summary>
        /// Gets the view for BcContext.PapermakingOrder.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView23()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing PapermakingOrder
        [BookCompanyManagement.DAL.PaperMakingOrder](T1.PaperMakingOrder_PaperMakingOrderId, T1.PaperMakingOrder_PaperMakingOrderName, T1.PaperMakingOrder_PaperMount, T1.PaperMakingOrder_OrderStatus, T1.PaperMakingOrder_CreateDateTime, T1.PaperMakingOrder_CopmleteDateTime, T1.PaperMakingOrder_BookCompanyId, T1.PaperMakingOrder_PaperId, T1.PaperMakingOrder_PrintShopId) WITH 
        RELATIONSHIP(CREATEREF(BcContext.Paperspec, ROW(T1.[PaperSpec_PaperMakingOrders.PaperSpec_PaperMakingOrders_Source.PaperSpecId]),[BookCompanyManagement.DAL.PaperSpec]),[BookCompanyManagement.DAL.PaperSpec_PaperMakingOrders],PaperSpec_PaperMakingOrders_Target,PaperSpec_PaperMakingOrders_Source) 
    FROM (
        SELECT 
            T.PaperMakingOrderId AS PaperMakingOrder_PaperMakingOrderId, 
            T.PaperMakingOrderName AS PaperMakingOrder_PaperMakingOrderName, 
            T.PaperMount AS PaperMakingOrder_PaperMount, 
            CAST(T.OrderStatus AS [BookCompanyManagement.DAL.PaperOrderStatus]) AS PaperMakingOrder_OrderStatus, 
            T.CreateDateTime AS PaperMakingOrder_CreateDateTime, 
            T.CopmleteDateTime AS PaperMakingOrder_CopmleteDateTime, 
            T.BookCompanyId AS PaperMakingOrder_BookCompanyId, 
            T.PaperId AS PaperMakingOrder_PaperId, 
            T.PrintShopId AS PaperMakingOrder_PrintShopId, 
            True AS _from0, 
            T.PaperSpec_PaperSpecId AS [PaperSpec_PaperMakingOrders.PaperSpec_PaperMakingOrders_Source.PaperSpecId]
        FROM CodeFirstDatabase.PaperMakingOrder AS T
    ) AS T1");
        }

        /// <summary>
        /// Gets the view for BcContext.PaperSpec_PaperMakingOrders.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView24()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing PaperSpec_PaperMakingOrders
        [BookCompanyManagement.DAL.PaperSpec_PaperMakingOrders](T3.[PaperSpec_PaperMakingOrders.PaperSpec_PaperMakingOrders_Source], T3.[PaperSpec_PaperMakingOrders.PaperSpec_PaperMakingOrders_Target])
    FROM (
        SELECT -- Constructing PaperSpec_PaperMakingOrders_Source
            CreateRef(BcContext.Paperspec, row(T2.[PaperSpec_PaperMakingOrders.PaperSpec_PaperMakingOrders_Source.PaperSpecId]), [BookCompanyManagement.DAL.PaperSpec]) AS [PaperSpec_PaperMakingOrders.PaperSpec_PaperMakingOrders_Source], 
            T2.[PaperSpec_PaperMakingOrders.PaperSpec_PaperMakingOrders_Target]
        FROM (
            SELECT -- Constructing PaperSpec_PaperMakingOrders_Target
                T1.[PaperSpec_PaperMakingOrders.PaperSpec_PaperMakingOrders_Source.PaperSpecId], 
                CreateRef(BcContext.PapermakingOrder, row(T1.[PaperSpec_PaperMakingOrders.PaperSpec_PaperMakingOrders_Target.PaperMakingOrderId]), [BookCompanyManagement.DAL.PaperMakingOrder]) AS [PaperSpec_PaperMakingOrders.PaperSpec_PaperMakingOrders_Target]
            FROM (
                SELECT 
                    T.PaperSpec_PaperSpecId AS [PaperSpec_PaperMakingOrders.PaperSpec_PaperMakingOrders_Source.PaperSpecId], 
                    T.PaperMakingOrderId AS [PaperSpec_PaperMakingOrders.PaperSpec_PaperMakingOrders_Target.PaperMakingOrderId], 
                    True AS _from0
                FROM CodeFirstDatabase.PaperMakingOrder AS T
                WHERE T.PaperSpec_PaperSpecId IS NOT NULL
            ) AS T1
        ) AS T2
    ) AS T3");
        }

        /// <summary>
        /// Gets the view for BcContext.PaperNeeds.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView25()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing PaperNeeds
        [BookCompanyManagement.DAL.PaperNeed](T1.PaperNeed_PaperNeedId, T1.PaperNeed_PaperNeedName, T1.PaperNeed_PaperId, T1.PaperNeed_PaperNeedMount, T1.PaperNeed_BookPrintOrderId)
    FROM (
        SELECT 
            T.PaperNeedId AS PaperNeed_PaperNeedId, 
            T.PaperNeedName AS PaperNeed_PaperNeedName, 
            T.PaperId AS PaperNeed_PaperId, 
            T.PaperNeedMount AS PaperNeed_PaperNeedMount, 
            T.BookPrintOrderId AS PaperNeed_BookPrintOrderId, 
            True AS _from0
        FROM CodeFirstDatabase.PaperNeed AS T
    ) AS T1");
        }

        /// <summary>
        /// Gets the view for BcContext.BookInstocks.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView26()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing BookInstocks
        [BookCompanyManagement.DAL.BookInstock](T1.BookInstock_BookInstockId, T1.BookInstock_BookInstockNname, T1.BookInstock_BookMount, T1.BookInstock_PaperId, T1.BookInstock_PrintShopId)
    FROM (
        SELECT 
            T.BookInstockId AS BookInstock_BookInstockId, 
            T.BookInstockNname AS BookInstock_BookInstockNname, 
            T.BookMount AS BookInstock_BookMount, 
            T.PaperId AS BookInstock_PaperId, 
            T.PrintShopId AS BookInstock_PrintShopId, 
            True AS _from0
        FROM CodeFirstDatabase.BookInstock AS T
    ) AS T1");
        }
    }
}
