// <auto-generated />
namespace BookCompanyManagement.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class bookdeliveryorder2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(bookdeliveryorder2));
        
        string IMigrationMetadata.Id
        {
            get { return "201512170558102_bookdeliveryorder2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
